
#ifndef _CONSOLE_DEFS_H
#define _CONSOLE_DEFS_H


#define CONSOLE_CHAR_WIDTH 8
#define CONSOLE_CHAR_HEIGHT 16
#define CONSOLE_ROW_HEIGHT CONSOLE_CHAR_HEIGHT

#define RESOLUTION_W 640
#define RESOLUTION_H 480

#define CONSOLE_Y_OFFSET (CONSOLE_CHAR_HEIGHT-2)
#define CONSOLE_X_OFFSET  0

#define CONSOLE_WIDTH RESOLUTION_W
#define CONSOLE_LINES ((RESOLUTION_H-CONSOLE_Y_OFFSET)/CONSOLE_ROW_HEIGHT - 1)
#define CONSOLE_COLUMNS (CONSOLE_WIDTH/CONSOLE_CHAR_WIDTH)

#define FONT_NORMAL		0x0
#define FONT_HELPTEXT	0x1
#define FONT_HIGHLIGHT	0x2
#define FONT_HEADING	0x3
#define FONT_ERROR		0x4

#endif // _CONSOLE_DEFS_H
