
#include <stdio.h>
#include <stdlib.h>

#include "lodepng.h"

int main(int argc, char **argv)
{
	if (argc != 2) {
		fprintf(stderr, "Usage: mklogo logo.png\n");
		return -1;
	}
	
	unsigned error;
	unsigned char* image;
	unsigned width, height;
	
	error = lodepng_decode32_file(&image, &width, &height, argv[1]);
	if(error) {
		printf("error %u: %s\n", error, lodepng_error_text(error));
		return -2;
	}
	
	printf("\n/* This file is automatically generated, DO NOT EDIT! */\n\n#include \"raster.h\"\n\n"
			"int gumboot_logo_width = %d,\n\tgumboot_logo_height = %d,\nunsigned char gumboot_logo_pixels[] = {\n",
			width, height);
	
	// start emitting the pixel data
	int x,y;
	for(y=0;y<height;y++) {
		printf("\t\t0x%02X", image[y * width]);
		for(x=1;x<width;x++) {
			printf(",0x%02X", image[x + y * width]);
		}
		if (y != height -1)
			printf(",\n");
		else
			printf("\n");
	}
	
	// finish struct
	printf("\t};\n");
	
	free(image);

	return 0;
}
